
// This file has been generated by the GUI designer. Do not modify.
namespace FoT
{
	public partial class EnviroChooser2
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button button1;
		private global::Gtk.Button button2;
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Label label2;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Button button3;
		private global::Gtk.Button button4;
		private global::Gtk.Button button5;
		private global::Gtk.Fixed fixed3;
		private global::Gtk.Label label3;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Button button6;
		private global::Gtk.Button button7;
		private global::Gtk.Button button8;
		private global::Gtk.Fixed fixed4;
		private global::Gtk.Label label4;
		private global::Gtk.Label label1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Button button9;
		private global::Gtk.Button button10;
		private global::Gtk.Button button11;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Button button12;
		private global::Gtk.Button button13;
		private global::Gtk.Button button14;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Button button15;
		private global::Gtk.Button button16;
		private global::Gtk.Button button17;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Button button18;
		private global::Gtk.Button button19;
		private global::Gtk.Button button20;
		private global::Gtk.Button button21;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Button button22;
		private global::Gtk.Button button23;
		private global::Gtk.HBox hbox5;
		private global::Gtk.HBox hbox10;
		private global::Gtk.Button button24;
		private global::Gtk.Button button25;
		private global::Gtk.Button button26;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Button button27;
		private global::Gtk.Button button28;
		private global::Gtk.Button button29;
		private global::Gtk.HBox hbox12;
		private global::Gtk.Button button30;
		private global::Gtk.Button button31;
		private global::Gtk.Button button32;
		private global::Gtk.HBox hbox13;
		private global::Gtk.Button button33;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FoT.EnviroChooser2
			this.Name = "FoT.EnviroChooser2";
			this.Title = global::Mono.Unix.Catalog.GetString ("EnviroChooser2");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child FoT.EnviroChooser2.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Desktop");
			this.hbox1.Add (this.button1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Device");
			this.hbox1.Add (this.button2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button2]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox1.Add (this.fixed2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixed2]));
			w3.Position = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.WidthRequest = 200;
			this.label2.Name = "label2";
			this.label2.LabelProp = "< -- Select a type";
			this.hbox1.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label2]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("Windows");
			this.hbox2.Add (this.button3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button3]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button ();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString ("OSX");
			this.hbox2.Add (this.button4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button4]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString ("Other");
			this.hbox2.Add (this.button5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button5]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.hbox2.Add (this.fixed3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed3]));
			w9.Position = 3;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.WidthRequest = 200;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("< -- Select a OS");
			this.hbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label3]));
			w10.Position = 4;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button ();
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = global::Mono.Unix.Catalog.GetString ("Android");
			this.hbox3.Add (this.button6);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button6]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button ();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString ("iOS");
			this.hbox3.Add (this.button7);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button7]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button ();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString ("BB / WinPhone");
			this.hbox3.Add (this.button8);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button8]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.hbox3.Add (this.fixed4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.fixed4]));
			w15.Position = 3;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.WidthRequest = 200;
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("< -- Select a OS");
			this.hbox3.Add (this.label4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label4]));
			w16.Position = 4;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox2.Add (this.vbox1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox1]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label1]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button9 = new global::Gtk.Button ();
			this.button9.CanFocus = true;
			this.button9.Name = "button9";
			this.button9.UseUnderline = true;
			this.button9.Label = global::Mono.Unix.Catalog.GetString ("AND1");
			this.hbox4.Add (this.button9);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button9]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button10 = new global::Gtk.Button ();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseUnderline = true;
			this.button10.Label = global::Mono.Unix.Catalog.GetString ("AND2");
			this.hbox4.Add (this.button10);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button10]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.button11 = new global::Gtk.Button ();
			this.button11.CanFocus = true;
			this.button11.Name = "button11";
			this.button11.UseUnderline = true;
			this.button11.Label = global::Mono.Unix.Catalog.GetString ("AND3");
			this.hbox4.Add (this.button11);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.button11]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.button12 = new global::Gtk.Button ();
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			this.button12.UseUnderline = true;
			this.button12.Label = global::Mono.Unix.Catalog.GetString ("AND4");
			this.hbox9.Add (this.button12);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.button12]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.button13 = new global::Gtk.Button ();
			this.button13.CanFocus = true;
			this.button13.Name = "button13";
			this.button13.UseUnderline = true;
			this.button13.Label = global::Mono.Unix.Catalog.GetString ("AND5");
			this.hbox9.Add (this.button13);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.button13]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.button14 = new global::Gtk.Button ();
			this.button14.CanFocus = true;
			this.button14.Name = "button14";
			this.button14.UseUnderline = true;
			this.button14.Label = global::Mono.Unix.Catalog.GetString ("AND6");
			this.hbox9.Add (this.button14);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.button14]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			this.hbox4.Add (this.hbox9);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hbox9]));
			w26.Position = 3;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.button15 = new global::Gtk.Button ();
			this.button15.CanFocus = true;
			this.button15.Name = "button15";
			this.button15.UseUnderline = true;
			this.button15.Label = global::Mono.Unix.Catalog.GetString ("AND7");
			this.hbox6.Add (this.button15);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.button15]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.button16 = new global::Gtk.Button ();
			this.button16.CanFocus = true;
			this.button16.Name = "button16";
			this.button16.UseUnderline = true;
			this.button16.Label = global::Mono.Unix.Catalog.GetString ("iOS1");
			this.hbox6.Add (this.button16);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.button16]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.button17 = new global::Gtk.Button ();
			this.button17.CanFocus = true;
			this.button17.Name = "button17";
			this.button17.UseUnderline = true;
			this.button17.Label = global::Mono.Unix.Catalog.GetString ("BW2");
			this.hbox6.Add (this.button17);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.button17]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button18 = new global::Gtk.Button ();
			this.button18.CanFocus = true;
			this.button18.Name = "button18";
			this.button18.UseUnderline = true;
			this.button18.Label = global::Mono.Unix.Catalog.GetString ("BW1");
			this.hbox7.Add (this.button18);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button18]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button19 = new global::Gtk.Button ();
			this.button19.CanFocus = true;
			this.button19.Name = "button19";
			this.button19.UseUnderline = true;
			this.button19.Label = global::Mono.Unix.Catalog.GetString ("iOS3");
			this.hbox7.Add (this.button19);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button19]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button20 = new global::Gtk.Button ();
			this.button20.CanFocus = true;
			this.button20.Name = "button20";
			this.button20.UseUnderline = true;
			this.button20.Label = global::Mono.Unix.Catalog.GetString ("iOS4");
			this.hbox7.Add (this.button20);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button20]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button21 = new global::Gtk.Button ();
			this.button21.CanFocus = true;
			this.button21.Name = "button21";
			this.button21.UseUnderline = true;
			this.button21.Label = global::Mono.Unix.Catalog.GetString ("iOS2");
			this.hbox7.Add (this.button21);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.button21]));
			w33.Position = 3;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button22 = new global::Gtk.Button ();
			this.button22.CanFocus = true;
			this.button22.Name = "button22";
			this.button22.UseUnderline = true;
			this.button22.Label = global::Mono.Unix.Catalog.GetString ("Win1");
			this.hbox8.Add (this.button22);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.button22]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button23 = new global::Gtk.Button ();
			this.button23.CanFocus = true;
			this.button23.Name = "button23";
			this.button23.UseUnderline = true;
			this.button23.Label = global::Mono.Unix.Catalog.GetString ("BW4");
			this.hbox8.Add (this.button23);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.button23]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			this.hbox7.Add (this.hbox8);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hbox8]));
			w36.Position = 4;
			w36.Expand = false;
			w36.Fill = false;
			this.hbox6.Add (this.hbox7);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.hbox7]));
			w37.Position = 3;
			w37.Expand = false;
			w37.Fill = false;
			this.hbox4.Add (this.hbox6);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hbox6]));
			w38.Position = 4;
			w38.Expand = false;
			w38.Fill = false;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.button24 = new global::Gtk.Button ();
			this.button24.CanFocus = true;
			this.button24.Name = "button24";
			this.button24.UseUnderline = true;
			this.button24.Label = global::Mono.Unix.Catalog.GetString ("BW3");
			this.hbox10.Add (this.button24);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.button24]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.button25 = new global::Gtk.Button ();
			this.button25.CanFocus = true;
			this.button25.Name = "button25";
			this.button25.UseUnderline = true;
			this.button25.Label = global::Mono.Unix.Catalog.GetString ("Win2");
			this.hbox10.Add (this.button25);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.button25]));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.button26 = new global::Gtk.Button ();
			this.button26.CanFocus = true;
			this.button26.Name = "button26";
			this.button26.UseUnderline = true;
			this.button26.Label = global::Mono.Unix.Catalog.GetString ("Win3");
			this.hbox10.Add (this.button26);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.button26]));
			w42.Position = 2;
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.button27 = new global::Gtk.Button ();
			this.button27.CanFocus = true;
			this.button27.Name = "button27";
			this.button27.UseUnderline = true;
			this.button27.Label = global::Mono.Unix.Catalog.GetString ("Win4");
			this.hbox11.Add (this.button27);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.button27]));
			w43.Position = 0;
			w43.Expand = false;
			w43.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.button28 = new global::Gtk.Button ();
			this.button28.CanFocus = true;
			this.button28.Name = "button28";
			this.button28.UseUnderline = true;
			this.button28.Label = global::Mono.Unix.Catalog.GetString ("OSX1");
			this.hbox11.Add (this.button28);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.button28]));
			w44.Position = 1;
			w44.Expand = false;
			w44.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.button29 = new global::Gtk.Button ();
			this.button29.CanFocus = true;
			this.button29.Name = "button29";
			this.button29.UseUnderline = true;
			this.button29.Label = global::Mono.Unix.Catalog.GetString ("OSX2");
			this.hbox11.Add (this.button29);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.button29]));
			w45.Position = 2;
			w45.Expand = false;
			w45.Fill = false;
			this.hbox10.Add (this.hbox11);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.hbox11]));
			w46.Position = 3;
			w46.Expand = false;
			w46.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.button30 = new global::Gtk.Button ();
			this.button30.CanFocus = true;
			this.button30.Name = "button30";
			this.button30.UseUnderline = true;
			this.button30.Label = global::Mono.Unix.Catalog.GetString ("OSX3");
			this.hbox12.Add (this.button30);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.button30]));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.button31 = new global::Gtk.Button ();
			this.button31.CanFocus = true;
			this.button31.Name = "button31";
			this.button31.UseUnderline = true;
			this.button31.Label = global::Mono.Unix.Catalog.GetString ("OSX4");
			this.hbox12.Add (this.button31);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.button31]));
			w48.Position = 1;
			w48.Expand = false;
			w48.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.button32 = new global::Gtk.Button ();
			this.button32.CanFocus = true;
			this.button32.Name = "button32";
			this.button32.UseUnderline = true;
			this.button32.Label = global::Mono.Unix.Catalog.GetString ("Other1");
			this.hbox12.Add (this.button32);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.button32]));
			w49.Position = 2;
			w49.Expand = false;
			w49.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.button33 = new global::Gtk.Button ();
			this.button33.CanFocus = true;
			this.button33.Name = "button33";
			this.button33.UseUnderline = true;
			this.button33.Label = global::Mono.Unix.Catalog.GetString ("Other2");
			this.hbox13.Add (this.button33);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.button33]));
			w50.Position = 0;
			w50.Expand = false;
			w50.Fill = false;
			this.hbox12.Add (this.hbox13);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.hbox13]));
			w51.Position = 3;
			w51.Expand = false;
			w51.Fill = false;
			this.hbox10.Add (this.hbox12);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.hbox12]));
			w52.Position = 4;
			w52.Expand = false;
			w52.Fill = false;
			this.hbox5.Add (this.hbox10);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hbox10]));
			w53.Position = 0;
			w53.Expand = false;
			w53.Fill = false;
			this.vbox3.Add (this.hbox5);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
			w54.Position = 1;
			w54.Expand = false;
			w54.Fill = false;
			this.vbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
			w55.Position = 2;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 952;
			this.DefaultHeight = 303;
			this.button3.Hide ();
			this.button4.Hide ();
			this.button5.Hide ();
			this.label3.Hide ();
			this.button6.Hide ();
			this.button7.Hide ();
			this.button8.Hide ();
			this.label4.Hide ();
			this.Show ();
			this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
			this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
			this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
			this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
			this.button5.Clicked += new global::System.EventHandler (this.OnButton5Clicked);
			this.button6.Clicked += new global::System.EventHandler (this.OnButton6Clicked);
			this.button7.Clicked += new global::System.EventHandler (this.OnButton7Clicked);
			this.button8.Clicked += new global::System.EventHandler (this.OnButton8Clicked);
		}
	}
}
