
// This file has been generated by the GUI designer. Do not modify.
namespace FoT
{
	public partial class EnviroChooser2
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action DesktopAction;
		private global::Gtk.Action DeviceAction;
		private global::Gtk.Action WindowsAction;
		private global::Gtk.Action OSXAction;
		private global::Gtk.Action OtherAction;
		private global::Gtk.Action AndroidAction;
		private global::Gtk.Action iOSAction;
		private global::Gtk.Action BBWinPhoneAction;
		private global::Gtk.VBox vbox2;
		private global::Gtk.VBox vbox3;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.MenuBar menubar2;
		private global::Gtk.MenuBar menubar3;
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Label label1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget FoT.EnviroChooser2
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.DesktopAction = new global::Gtk.Action ("DesktopAction", global::Mono.Unix.Catalog.GetString ("Desktop"), null, null);
			this.DesktopAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Desktop");
			w1.Add (this.DesktopAction, null);
			this.DeviceAction = new global::Gtk.Action ("DeviceAction", global::Mono.Unix.Catalog.GetString ("Device"), null, null);
			this.DeviceAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Device");
			w1.Add (this.DeviceAction, null);
			this.WindowsAction = new global::Gtk.Action ("WindowsAction", global::Mono.Unix.Catalog.GetString ("Windows"), null, null);
			this.WindowsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Windows");
			w1.Add (this.WindowsAction, null);
			this.OSXAction = new global::Gtk.Action ("OSXAction", global::Mono.Unix.Catalog.GetString ("OSX"), null, null);
			this.OSXAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("OSX");
			w1.Add (this.OSXAction, null);
			this.OtherAction = new global::Gtk.Action ("OtherAction", global::Mono.Unix.Catalog.GetString ("Other"), null, null);
			this.OtherAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Other");
			w1.Add (this.OtherAction, null);
			this.AndroidAction = new global::Gtk.Action ("AndroidAction", global::Mono.Unix.Catalog.GetString ("Android"), null, null);
			this.AndroidAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Android");
			w1.Add (this.AndroidAction, null);
			this.iOSAction = new global::Gtk.Action ("iOSAction", global::Mono.Unix.Catalog.GetString ("iOS"), null, null);
			this.iOSAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("iOS");
			w1.Add (this.iOSAction, null);
			this.BBWinPhoneAction = new global::Gtk.Action ("BBWinPhoneAction", global::Mono.Unix.Catalog.GetString ("BB / WinPhone"), null, null);
			this.BBWinPhoneAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("BB / WinPhone");
			w1.Add (this.BBWinPhoneAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "FoT.EnviroChooser2";
			this.Title = global::Mono.Unix.Catalog.GetString ("EnviroChooser2");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child FoT.EnviroChooser2.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar1\'><menu name=\'DesktopAction\' action=\'DesktopAction\'/><" +
			"menu name=\'DeviceAction\' action=\'DeviceAction\'/></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox3.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar2\'><menu name=\'WindowsAction\' action=\'WindowsAction\'/><" +
			"menu name=\'OSXAction\' action=\'OSXAction\'/><menu name=\'OtherAction\' action=\'Other" +
			"Action\'/></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.vbox3.Add (this.menubar2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.menubar2]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar3\'><menu name=\'AndroidAction\' action=\'AndroidAction\'/><" +
			"menu name=\'iOSAction\' action=\'iOSAction\'/><menu name=\'BBWinPhoneAction\' action=\'" +
			"BBWinPhoneAction\'/></menubar></ui>");
			this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar3")));
			this.menubar3.Name = "menubar3";
			this.vbox3.Add (this.menubar3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.menubar3]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.HeightRequest = 100;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vbox2.Add (this.fixed1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.fixed1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label1]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 423;
			this.DefaultHeight = 303;
			this.menubar2.Hide ();
			this.menubar3.Hide ();
			this.Show ();
			this.DesktopAction.Activated += new global::System.EventHandler (this.OnDesktopActionActivated);
		}
	}
}
