
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action newAction;
	private global::Gtk.Action clearAction;
	private global::Gtk.Action DevEnviromentAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.HBox hbox3;
	private global::Gtk.HSeparator hseparator7;
	private global::Gtk.Label label1;
	private global::Gtk.HSeparator hseparator6;
	private global::Gtk.Button button2;
	private global::Gtk.Label label2;
	private global::Gtk.HSeparator hseparator3;
	private global::Gtk.Label labelClient1;
	private global::Gtk.Entry entry1;
	private global::Gtk.Label labelProject1;
	private global::Gtk.Entry entry2;
	private global::Gtk.Label labelClient2;
	private global::Gtk.Entry entry3;
	private global::Gtk.Label labelProject2;
	private global::Gtk.Entry entry4;
	private global::Gtk.Button button3;
	private global::Gtk.HBox hbox1;
	private global::Gtk.CheckButton checkbutton1;
	private global::Gtk.CheckButton checkbutton2;
	private global::Gtk.CheckButton checkbutton3;
	private global::Gtk.HSeparator hseparator4;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Button buttonQuit;
	private global::Gtk.Button button1;
	private global::Gtk.Button buttonContinue;
	private global::Gtk.HSeparator hseparator5;
	private global::Gtk.Label label3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.newAction = new global::Gtk.Action ("newAction", global::Mono.Unix.Catalog.GetString ("File"), null, "gtk-new");
		this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.newAction, null);
		this.clearAction = new global::Gtk.Action ("clearAction", global::Mono.Unix.Catalog.GetString ("Reset"), null, "gtk-clear");
		this.clearAction.HideIfEmpty = false;
		this.clearAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Reset");
		w1.Add (this.clearAction, null);
		this.DevEnviromentAction = new global::Gtk.Action ("DevEnviromentAction", global::Mono.Unix.Catalog.GetString ("Dev Enviroment"), null, null);
		this.DevEnviromentAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Dev Enviroment");
		w1.Add (this.DevEnviromentAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.WidthRequest = 500;
		this.HeightRequest = 600;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("FoT Application");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
		this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(9));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name=\'menubar1\'><menu name=\'newAction\' action=\'newAction\'><menuitem " +
		"name=\'DevEnviromentAction\' action=\'DevEnviromentAction\'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox2.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hseparator7 = new global::Gtk.HSeparator ();
		this.hseparator7.Name = "hseparator7";
		this.hbox3.Add (this.hseparator7);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hseparator7]));
		w3.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Either select a file path or leave to default");
		this.hbox3.Add (this.label1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hseparator6 = new global::Gtk.HSeparator ();
		this.hseparator6.Name = "hseparator6";
		this.hbox3.Add (this.hseparator6);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hseparator6]));
		w5.Position = 2;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.WidthRequest = 150;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("File Directory Chooser");
		this.vbox2.Add (this.button2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button2]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.vbox2.Add (this.label2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label2]));
		w8.Position = 3;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator ();
		this.hseparator3.Name = "hseparator3";
		this.vbox2.Add (this.hseparator3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator3]));
		w9.Position = 4;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.labelClient1 = new global::Gtk.Label ();
		this.labelClient1.Name = "labelClient1";
		this.labelClient1.LabelProp = global::Mono.Unix.Catalog.GetString ("Client name");
		this.labelClient1.Wrap = true;
		this.labelClient1.Justify = ((global::Gtk.Justification)(3));
		this.vbox1.Add (this.labelClient1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.labelClient1]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.vbox1.Add (this.entry1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.entry1]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.labelProject1 = new global::Gtk.Label ();
		this.labelProject1.Name = "labelProject1";
		this.labelProject1.LabelProp = global::Mono.Unix.Catalog.GetString ("Project name");
		this.labelProject1.Wrap = true;
		this.vbox1.Add (this.labelProject1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.labelProject1]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.vbox1.Add (this.entry2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.entry2]));
		w14.Position = 4;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.labelClient2 = new global::Gtk.Label ();
		this.labelClient2.Name = "labelClient2";
		this.labelClient2.LabelProp = global::Mono.Unix.Catalog.GetString ("Test URL (One version only)");
		this.labelClient2.Wrap = true;
		this.vbox1.Add (this.labelClient2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.labelClient2]));
		w15.Position = 5;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.vbox1.Add (this.entry3);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.entry3]));
		w16.Position = 6;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.labelProject2 = new global::Gtk.Label ();
		this.labelProject2.Name = "labelProject2";
		this.labelProject2.LabelProp = global::Mono.Unix.Catalog.GetString ("Build Version (One version only)");
		this.labelProject2.Wrap = true;
		this.vbox1.Add (this.labelProject2);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.labelProject2]));
		w17.Position = 7;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry4 = new global::Gtk.Entry ();
		this.entry4.CanFocus = true;
		this.entry4.Name = "entry4";
		this.entry4.IsEditable = true;
		this.entry4.InvisibleChar = '●';
		this.vbox1.Add (this.entry4);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.entry4]));
		w18.Position = 8;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Environment Chooser (Dev)");
		this.vbox1.Add (this.button3);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.button3]));
		w19.Position = 9;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.checkbutton1 = new global::Gtk.CheckButton ();
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString ("Scripting & Planning");
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.hbox1.Add (this.checkbutton1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.checkbutton1]));
		w20.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.checkbutton2 = new global::Gtk.CheckButton ();
		this.checkbutton2.CanFocus = true;
		this.checkbutton2.Name = "checkbutton2";
		this.checkbutton2.Label = global::Mono.Unix.Catalog.GetString ("Test Execution");
		this.checkbutton2.Active = true;
		this.checkbutton2.DrawIndicator = true;
		this.checkbutton2.UseUnderline = true;
		this.hbox1.Add (this.checkbutton2);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.checkbutton2]));
		w21.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.checkbutton3 = new global::Gtk.CheckButton ();
		this.checkbutton3.CanFocus = true;
		this.checkbutton3.Name = "checkbutton3";
		this.checkbutton3.Label = global::Mono.Unix.Catalog.GetString ("IVs & Retest");
		this.checkbutton3.DrawIndicator = true;
		this.checkbutton3.UseUnderline = true;
		this.hbox1.Add (this.checkbutton3);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.checkbutton3]));
		w22.Position = 2;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w23.Position = 10;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator4 = new global::Gtk.HSeparator ();
		this.hseparator4.Name = "hseparator4";
		this.vbox1.Add (this.hseparator4);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator4]));
		w24.Position = 11;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.buttonQuit = new global::Gtk.Button ();
		this.buttonQuit.TooltipMarkup = "Quit application";
		this.buttonQuit.WidthRequest = 150;
		this.buttonQuit.CanFocus = true;
		this.buttonQuit.Name = "buttonQuit";
		this.buttonQuit.UseUnderline = true;
		this.buttonQuit.Label = global::Mono.Unix.Catalog.GetString ("Quit");
		this.hbox2.Add (this.buttonQuit);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonQuit]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.WidthRequest = 150;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Reset All");
		this.hbox2.Add (this.button1);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button1]));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.buttonContinue = new global::Gtk.Button ();
		this.buttonContinue.TooltipMarkup = "Create client and project folders";
		this.buttonContinue.WidthRequest = 150;
		this.buttonContinue.CanFocus = true;
		this.buttonContinue.Name = "buttonContinue";
		this.buttonContinue.UseUnderline = true;
		this.buttonContinue.Label = global::Mono.Unix.Catalog.GetString ("Create Folders");
		this.hbox2.Add (this.buttonContinue);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonContinue]));
		w27.Position = 2;
		w27.Expand = false;
		w27.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w28.Position = 12;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator5 = new global::Gtk.HSeparator ();
		this.hseparator5.Name = "hseparator5";
		this.vbox1.Add (this.hseparator5);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator5]));
		w29.Position = 13;
		w29.Expand = false;
		w29.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Notes:\nDo not add / , . \\ into Client or Project name fields \nFields can be left " +
		"blank");
		this.label3.Wrap = true;
		this.vbox1.Add (this.label3);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label3]));
		w30.Position = 14;
		w30.Expand = false;
		w30.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 500;
		this.DefaultHeight = 600;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.clearAction.Activated += new global::System.EventHandler (this.OnClearActionActivated);
		this.DevEnviromentAction.Activated += new global::System.EventHandler (this.OnDevEnviromentActionActivated);
		this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
		this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
		this.buttonQuit.Clicked += new global::System.EventHandler (this.OnButtonQuitClicked);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		this.buttonContinue.Clicked += new global::System.EventHandler (this.OnButtonContinueClicked);
	}
}
